name: Build TDLib with Java Bindings

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y g++ make cmake git zlib1g-dev libssl-dev openjdk-11-jdk

      - name: Build TDLib with Java Bindings
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DTD_ENABLE_JAVA_BINDINGS=ON ..
          cmake --build . --target install

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TDLib-Java-Bindings
          path: |
            build/java/tdjni.so
            build/java/td/tdlib.jar
