name: Build TDLib with Java Bindings

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Dependencies
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y g++ make cmake git zlib1g-dev libssl-dev openjdk-11-jdk gperf

      # Step 3: Build TDLib with Java Bindings
      - name: Build TDLib with Java Bindings
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DTD_ENABLE_JAVA_BINDINGS=ON \
                -DCMAKE_INSTALL_PREFIX=$(pwd)/install ..
          cmake --build . --target td_generate_java_api
          cmake --build . --target tdjni
          cmake --build . --target install

      # Step 4: Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TDLib-Java-Bindings
          path: |
            build/install/lib/libtdjson.so
            build/install/lib/libtdjson_static.a
            build/install/lib/libtdclient.a
            build/java/tdjni.so
            build/java/td/tdlib.jar
