name: Build TDLib

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y g++ make cmake git zlib1g-dev libssl-dev gperf

      - name: Build TDLib
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/install ..
          cmake --build . --target install

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TDLib
          path: install/
